# App configuration
App:
  id: "catalyst-backend-task"
  name: "Catalyst Backend Task"
Api:
  port: 3000
  hostname: 0.0.0.0
DbConfig:
  dialect: "mysql"
  connectionString: "root:zxasqw12@tcp(localhost:3306)/catalyst_backend_task?charset=utf8mb4&parseTime=True&loc=Local&multiStatements=true"
  maxOpenConn: 5
  maxIdleConn: 1
  maxConnLifetime: 10
